INSERT INTO EMPLOYMENT_TYPE(ID, NAME)
VALUES (1, 'Full Time Employee');
INSERT INTO EMPLOYMENT_TYPE(ID, NAME)
VALUES (2, 'Part Time Employee');
INSERT INTO EMPLOYMENT_TYPE(ID, NAME)
VALUES (3, 'Contractor');