INSERT INTO DEPARTMENT(ID, NAME)
VALUES (1, 'Technology consulting');
INSERT INTO DEPARTMENT(ID, NAME)
VALUES (2, 'Quality assurance');
INSERT INTO DEPARTMENT(ID, NAME)
VALUES (3, 'Human resources');
INSERT INTO DEPARTMENT(ID, NAME)
VALUES (4, 'Managed services');
INSERT INTO DEPARTMENT(ID, NAME)
VALUES (5, 'Management');